### ISSUE TITLE
need clarification

### ISSUE THREAD

**Issue by Sarfarazsajjad** [heqian/DHTServer#1]
please explain, which file needs to be copied and renamed as you mentioned in second and third steps

2.Compile the C program described in above "Hardware Tutorial";
3.Rename the binary program to "dht" and put it in the project folder;

**Comment by heqian** [comment]
Added the source code links in the instruction. Please take a look.

**Comment by Sarfarazsajjad** [comment]
how to compile these files (source code: Raspberry Pi & Raspberry Pi 2). I mean which compiler will be used to compile it and are there any necessary steps required to compile these files

**Comment by heqian** [comment]
gcc with C99 enabled should be able to compile it. You need to clone the whole project https://github.com/adafruit/Adafruit_Python_DHT because some required libraries are in the parent folder. If you are using Pi 1st gen, you can use the bin I compiled one year ago:

![dht](https://cloud.githubusercontent.com/assets/531639/7573641/27bcca14-f7f5-11e4-9bd6-81e1828f54c9.jpg)

(👆 is not a JPG image file, it's a bin file. Click to download it and rename it to "dht".)

**Comment by Sarfarazsajjad** [comment]
thank you so much, I really appreciate your help

**Comment by heqian** [comment]
No problem. :)
